# Generated by Django 5.0.4 on 2024-05-12 16:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('icon', models.ImageField(null=True, upload_to='status/icon/')),
                ('background', models.CharField(max_length=255, unique=True)),
                ('color', models.CharField(max_length=255)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='Untitled', max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('plane_finished_time', models.DateTimeField(blank=True, null=True, verbose_name='Планируемое время завершения задачи')),
                ('real_finished_time', models.DateTimeField(blank=True, null=True, verbose_name='Реальное время завершения задачи')),
                ('status_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='task.status')),
                ('task_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='same_task', to='task.task')),
            ],
        ),
    ]
